services:
  web:
    build: .
    command: gunicorn wsgi:app --bind 0.0.0.0:5000 --workers 1 --reload --log-level debug --error-logfile - --access-logfile -
    volumes:
      - .:/app
      - type: bind
        source: "C:/Users/bruni/OneDrive/Documentos/MestradoDocs/Projeto"
        target: /app/data
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
